name: Actions Test

on:
  workflow_dispatch:
    inputs:
      runnerOS:
        required: false
        default: self-hosted
        type: choice
        options:
        - Ubuntu
        - macOS
        - self-hosted
concurrency:
  group: "test: ${{ github.workflow }}"
  cancel-in-progress: true
jobs:

  test:
    runs-on: [self-hosted, "${{ inputs.runnerOS }}"]
    steps:
    - name: Pickup
      id: pickup
      run: echo "action ${{github.action}} \#${{github.run_id}} triggered by ${{github.actor}} acknowledged by ${{runner.os}} ${{runner.arch}} runner ${{runner.name}}"
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
    - name: Repo Size
      id: size
      run: du -h --total | grep total
    - name: Report
      run: echo "pickup ${{steps.pickup.outcome}}, checkout ${{steps.checkout.outcome}}, size ${{steps.size.outcome}}"
  
  
